### ISSUE TITLE
Point engineering.khanacademy.org (or whatever) to the site.

### ISSUE THREAD

**Issue by itsjohncs** [Khan/engblog#10]
I think I remember reading that GitHub's CDN won't function correctly if we point at a specific set of IPs, so I'll want to read up on that.

I'm also not sure how much I like `engblog.khanacademy.org` as the domain... Maybe just `eng`, or `engineering`, or `dev`...

**Comment by mroth** [comment]
Luckily for a subdomain, Github Pages is pretty straightforward, you can use a `CNAME` record pointing to `foobar.github.io` instead of an IP and then put an appropriate CNAME file in the repo (for apex-domains it's more annoying), see:
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

P.S. I _personally_ like `engineering.khanacademy.org` (which matches the current masthead you have), `dev.*` makes me think of a dev/staging version of the site.

**Comment by itsjohncs** [comment]
Oh sweet, that sounds simple enough. I'll open up a support ticket since I have no clue who controls our name servers.

And after reading your comment I agree, `engineering.khanacademy.org` seems like the best choice. It seems a bit long for someone to type in, but that doesn't seem like a big deal.

**Comment by xymostech** [comment]
We use Amazon's Route 53 to manage our DNS, the configuration is at https://github.com/Khan/network-config/tree/master/dns. Someone probably needs to actually go into Route 53 after changing it there, though.

**Comment by itsjohncs** [comment]
[I opened up a diff](https://phabricator.khanacademy.org/D18034) to our network config, waiting on that now.
